name: Publish Docker Images to Docker Hub

# 此工作流程在master分支有push操作时触发。
on:
  workflow_dispatch:  # 支持手动触发
  push:
    branches: [ master ]

# 定义推送到Docker Hub的镜像名称。
# 请将 'YOUR_DOCKERHUB_USERNAME' 替换为您的Docker Hub用户名或在GitHub Secrets中设置。
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} # GitHub仓库的Settings -> Secrets and variables -> Actions中配置此变量，或直接在此处填写
  BACKEND_IMAGE_NAME: team_oa_backend
  FRONTEND_IMAGE_NAME: team_oa_frontend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # 签出您的代码仓库。
        uses: actions/checkout@v4

      - name: Set up QEMU
        # 设置QEMU，用于支持多平台构建（可选）。
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        # 设置Docker Buildx，用于扩展Docker的构建功能。
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        # 登录到Docker Hub。
        # 需要在GitHub仓库的 Secrets中配置 DOCKERHUB_USERNAME 和 DOCKERHUB_TOKEN。
        # DOCKERHUB_TOKEN 通常是个人访问令牌 (Personal Access Token)。
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # 使用GitHub Secrets中的用户名
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # 使用GitHub Secrets中的Token

      - name: Build and push backend image
        # 构建并推送后端Docker镜像。
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile的上下文路径，对于后端是项目根目录
          file: ./Dockerfile # 后端Dockerfile的路径
          push: true # 推送到仓库
          tags: | # 镜像标签
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64 # 可选：构建多平台镜像

      - name: Build and push frontend image
        # 构建并推送前端Nginx Docker镜像。
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Dockerfile的上下文路径，对于前端是./frontend目录
          file: ./frontend/Dockerfile # 前端Dockerfile的路径
          push: true # 推送到仓库
          tags: | # 镜像标签
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64 # 可选：构建多平台镜像
